name: project deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 113
          script: |
            echo test > /tmp/test
            sudo -i
            rm -rf ./cicd
            git clone https://github.com/somminn/cicd.git
            apt install -y openjdk:17-jdk-slim
            .\gradlew bootjar
            echo 'COPY ./build/libs/back-0.0.1-SNAPSHOT.jar /app.jar
                  CMD ["java","-jar","/app.jar"]
                  EXPOSE 8080' > Dockerfile
            docker build --tag cowmin/backend:v1 .
