name: project deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 113
          script: |
            rm -rf ./cicd
            git clone https://github.com/somminn/cicd.git
            cd ./cicd
            chmod 755 ./gradlew
            ./gradlew bootjar
            docker image prune -f
            docker build --tag cowmin/backend:v3 .
            docker run -d --name back -p 8080:8080 cowmin/backend:latest
